title: Site

sections:
  pages:
    type: pages
    label: Content
    layout: cards
    templates:
      - book
      - comic
    
  fields:
    type: fields
    label: Settings
    fields:
      line:
        type: line
      heading:
        type: headline
        label: Settings
      name:
        type: text
        label: Name
      logo:
        type: files
        label: Logo
        width: 1/2
      logotoggle:
        type: toggle
        label: Show Logo?
        width: 1/6
      attribution:
        type: toggle
        label: Show attribution at the bottom of the page?
        width: 1/3
      showtypebadge:
        type: toggle
        label: Show Book/Comic badges on home page?
        default: true
        width: 1/3
